version: "3.3"

services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=kubernetes_django
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=MyStrongPass123!
      - PGUSER=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  webapp:
    image: ${IMAGE}:${TAG}
    command: python manage.py test
    environment: 
      - POSTGRES_HOST=db
      - POSTGRES_DB=kubernetes_django
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=MyStrongPass123!
      - DATABASE=postgres
    depends_on: 
      - db